### ISSUE TITLE
Domain broken

### ISSUE THREAD

**Issue by gohoski** [Sly-Little-Fox/scrat.cf#2]
The domain has been expired and now redirects to Freenom.

**Comment by Sly-Little-Fox** [comment]
> The domain has been expired and now redirects to Freenom.

Can't do anything, Freenom is always giving me errors when I try to renew or register a domain.

**Comment by gohoski** [comment]
Are you logged into an account?
--
Отправлено из Mail.ru для Android вторник, 26 апреля 2022г., 20:58 +03:00 от Sly-Little-Fox  ***@***.*** :

**Comment by gohoski** [comment]
> Are you logged into an account? -- Отправлено из Mail.ru для Android вторник, 26 апреля 2022г., 20:58 +03:00 от Sly-Little-Fox ***@***.*** :
> […](#)
> >The domain has been expired and now redirects to Freenom. Can't do anything, Freenom is always giving me errors when I try to renew or register a domain. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: . cf/issues/2/1110091565 @ github . com>

If not and you don't have one, then you won't register a one because Freenom disabled registration for like 1.5 years now. Thankfully I have an account so you can ask me to re-register the domain.

**Comment by Sly-Little-Fox** [comment]
> Are you logged into an account?
Yes I am.

**Comment by gohoski** [comment]
> Yes I am. Also why does your reply have so much autogenerated trash??

E-mail. Oh, and you can't re-register the domain. I just found out today. Some auto-scumbags will re-register your domain automatically and put a scam website.

**Comment by Sly-Little-Fox** [comment]
> > Yes I am. Also why does your reply have so much autogenerated trash??
> 
> E-mail. Oh, and you can't re-register the domain. I just found out today. Some auto-scumbags will re-register your domain automatically and put a scam website.

Yeah... :neutral_face:

**Comment by Sly-Little-Fox** [comment]
smh can't be resolved
